# Generated by Django 4.1.2 on 2023-06-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_tipo_alter_obras_imagen_obras_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obras',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
