# Generated by Django 4.1.2 on 2023-07-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_obras_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazadp')], default=1, max_length=255),
        ),
    ]
