# Generated by Django 4.1.2 on 2023-07-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_alter_estado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='mensaje',
            field=models.TextField(default=''),
        ),
    ]
