# Generated by Django 4.1.2 on 2023-07-08 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_obras_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='cliente.estado'),
        ),
    ]
